spring:
  application:
    name: membership-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: user
    password:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #  show_sql: true
        format_sql: true
        use_sql_comments: true


